# Implementation of Shell Sort

#### Algorithm

In [111]:
def shellsort(arr):
    gap = 1
    gaps = [1]
    
    while gap < len(arr):
        gap = 3*gap+1
        gaps.append(gap)
        
    for inc in gaps[::-1]:
        for substart in range(inc):
            sortedsub = insort([value for value in arr[substart::inc] if value])
            arr[substart::inc] = sortedsub
            
        print("shell sort at increment {}:".format(inc))
        print("\t"*3, arr)
            
    

In [112]:
# Insertion sort for sub-array
def insort(arr):
    for lead in range(1,len(arr)):
        val = arr.pop(lead)
        slot = lead
        if val > arr[slot-1]:
            arr.insert(slot, val)
            continue
        while val < arr[slot-1] and slot > 0:
            slot -= 1
        arr.insert(slot, val)
    return arr

#### Results

In [113]:
import numpy as np

arr = np.random.randint(1,50,20)
print("Random Array:")
arr

Random Array:


array([44, 12, 45, 34, 42, 40, 34, 22, 26, 28, 31,  5,  1, 31, 24, 25,  3,
       34, 22, 48])

In [114]:
shellsort(arr)

shell sort at increment 40:
			 [44 12 45 34 42 40 34 22 26 28 31  5  1 31 24 25  3 34 22 48]
shell sort at increment 13:
			 [31 12 25  3 34 22 34 22 26 28 31  5  1 44 24 45 34 42 40 48]
shell sort at increment 4:
			 [ 1 12 24  3 26 22 25  5 31 28 31 22 34 42 34 45 34 44 40 48]
shell sort at increment 1:
			 [ 1  3  5 12 22 22 24 25 26 28 31 31 34 34 34 40 42 44 45 48]
